version: '3'

services:
################################
#   Setup react js container
################################
  frontend:
    # image: mealio/mealio_frontend:latest
    # container_name: frontend
    build: ./frontend/cibus
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/cibus/public:/app/public
      - ./frontend/cibus/src:/app/src
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    depends_on:
      - frontend
      - backend
################################
#   Setup backend container
################################
  backend:
    # image: mealio/mealio_backend:latest
    # container_name: backend
    build: './backend/cibus-backend'
    # command: nodemon --watch . -e js ./backend/cibus-backend/server.js
    # command: nodemon ./backend/cibus-backend/server.js
    # command: nodemon --legacy-watch server.js
    env_file:
      - environment
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    expose:
      - 3001
    ports: 
      - 3001:3001
    volumes:
      - ./backend/cibus-backend:/usr/src/app
      - ./backend/cibus-backend/config:/usr/src/app/config
      - ./backend/cibus-backend/lib:/usr/src/app/lib
      - ./backend/cibus-backend/routes:/usr/src/app/routes
      - ./backend/cibus-backend/setup:/usr/src/app/setup
      - ./backend/cibus-backend/utils:/usr/src/app/utils
    depends_on:
      - rethink

  rethink:
    image: rethinkdb
    expose:
      - 29015
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"