version: '3'

services:
################################
#   Setup react js container
################################
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./frontend/src:/app/src
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    depends_on:
      - frontend
      - backend
################################
#   Setup backend container
################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - environment
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    ports:
      - 3001:3001
    volumes:
      - ./backend/config:/usr/src/app/config
      - ./backend/lib:/usr/src/app/lib
      - ./backend/routes:/usr/src/app/routes
      - ./backend/setup:/usr/src/app/setup
      - ./backend/utils:/usr/src/app/utils
      - ./backend/images:/usr/src/app/images
      - ./backend/parsers:/usr/src/app/parsers
    depends_on:
      - rethink

  rethink:
    image: rethinkdb
    expose:
      - 29015
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"