version: '3'

services:
################################
#   Setup react js container
################################
  frontend:
    build: ./frontend/cibus
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/cibus:/app
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - '443:443'
    depends_on: 
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
################################
#   Setup backend container
################################
  backend:
    build: './backend/cibus-backend'
    # command: nodemon --watch . -e js ./backend/cibus-backend/server.js
    # command: nodemon ./backend/cibus-backend/server.js
    command: nodemon --legacy-watch server.js
    env_file:
      - environment
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    expose:
      - 3001
    ports: 
      - 3001:3001
    volumes:
      - ./backend/cibus-backend:/usr/src/app
      - ./backend/cibus-backend/config:/usr/src/app/config
      - ./backend/cibus-backend/lib:/usr/src/app/lib
      - ./backend/cibus-backend/routes:/usr/src/app/routes
      - ./backend/cibus-backend/setup:/usr/src/app/setup
      - ./backend/cibus-backend/utils:/usr/src/app/utils
    depends_on:
      - rethink

  rethink:
    image: rethinkdb
    expose:
      - 29015
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"