# Stage 1 - the build process
FROM node:12.2.0-alpine as build-deps
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

# Stage 2 - the production environment
#FROM nginx:1.12-alpine
FROM mealio/frontend_server
#COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
COPY --from=build-deps /usr/src/app/build /app/build
EXPOSE 8800
#CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "run", "start"]