version: '3'

services:
################################
#   Setup react js container
################################
  frontend:
    container_name: frontend
    image: mealio/mealio_frontend:latest
    # command: npm run prod
    # expose:
    #   - 3000
    ports:
      - 80:80
################################
#   Setup nginx load balancer
################################
  # nginx:
  #   image: nginx:1.13 # this will use the latest version of 1.13.x
  #   ports:
  #     - '80:80' # expose 80 on host and sent to 80 in container
  #     - '443:443'
  #   depends_on: 
  #     - frontend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
################################
#   Setup backend container
################################
  backend:
    container_name: backend
    image: mealio/mealio_backend:latest
    # command: nodemon --watch . -e js ./backend/cibus-backend/server.js
    # command: nodemon ./backend/cibus-backend/server.js
    env_file:
      - environment
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    expose:
      - 3001
    ports: 
      - 3001:3001
    depends_on:
      - rethink

  rethink:
    image: rethinkdb
    expose:
      - 29015
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"