version: '3'

services:
################################
#   Setup react js container
################################
  frontend:
    container_name: frontend
    image: mealio/mealio_frontend:latest
    # cap_drop:
      # - ALL
    ports:
      - 80:80
################################
#   Setup backend container
################################
  backend:
    container_name: backend
    image: mealio/mealio_backend:latest
    env_file:
      - environment
    # environment:
    #   CHOKIDAR_USEPOLLING: 'true'
    #   CHOKIDAR_INTERVAL: 300
    cap_drop:
      - ALL
    ports: 
      - 3001:3001
    depends_on:
      - rethink

  rethink:
    image: rethinkdb
    volumes: 
      - rethink_data:/rethink_data
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"

volumes:
  rethink_data:
    driver: local